In [0]:
from pandas import read_csv
dataframe = read_csv('glove_India.csv', header=0,engine='python',usecols=range(1,100))
dataframe.shape

(16441, 85)

In [0]:
#dataframe.iloc[16439,:]
dataframe = dataframe.iloc[0:16440,:]
dataframe.shape

#dataframe.iloc[16439,:]

(16440, 85)

In [0]:
dataframe.iloc[0,:]

In [0]:
dataframe.iloc[0,84]
dataframe.iloc[0,83]

'22.7909'

In [0]:
no_days=822
no_data_per_day=20
features=85
print(dataframe.shape)
#print(dataframe.head(1))
print(no_days*no_data_per_day)
if dataframe.shape[0] != no_days*no_data_per_day:
  print('Incorrect Data plz check')
else:
  print('Correct Data')

(16440, 85)
16440
Correct Data


In [0]:
dataset=dataframe.values
import numpy
for i in range(15542):
  if i%19 == 0:
    w=dataset[i:i+19,:]
    u=numpy.unique(w[:,0])

In [0]:
print(dataframe.shape)
#print(dataframe.iloc[1,:])
dataset = dataframe.values
dataset = dataset.reshape(no_days,no_data_per_day,features)# no. of days, days data, features
dataset = dataset.reshape(no_days,no_data_per_day*features)
print(dataset.shape)

(16440, 85)
(822, 1700)


In [0]:
import pandas as pd
pd.DataFrame(dataset).to_csv("india.csv")

In [0]:
from pandas import read_csv
dataframe = read_csv('india.csv', header=0,engine='python',usecols=range(1,2000))
dataframe.shape

(822, 1700)

In [0]:
import math
d = dataframe.values
print(d[0].shape)
print(d[0,1651],d[0,1652])
#print(d[0,172],d[0,173])
c=0
#for i in range(1652):
#  if math.isnan(d[0,i]):
#    c+=1
#    print(i);
#print(c)
    
c=0
for i in range(20):
  print(d[0,83+c],d[0,84+c])
  c+=85

(1700,)
3.986958317 3.986958317
22.7909 85.831
30.2108 74.9452
23.2166 72.6833
26.8392 80.9231
12.9172 74.85600000000001
23.3432 85.3094
30.7362 76.7884
11.6511 78.1586
26.3026 86.6612
28.8944 76.5891
26.1433 91.7896
22.2916 70.7932
28.6667 77.2167
28.6667 77.2167
30.9 75.85
15.4667 75.0167
13.0833 80.2833
13.0833 80.2833
27.45 83.1333
26.85 80.9167


No NAN no need to normalize

In [0]:
import math
for i in range(822):
  for j in range(1700):
    if math.isnan(d[i,j]):
      print(j)
      print(d[i,j],'=',d[i-1,j])
      d[i,j]=d[i-1,j]
      print(d[i,j],'=',d[i-1,j])

1443
nan = 11.1035
11.1035 = 11.1035
1444
nan = 79.655
79.655 = 79.655
1528
nan = 10.7639
10.7639 = 10.7639
1529
nan = 79.8445
79.8445 = 79.8445
1613
nan = 25.5966
25.5966 = 25.5966
1614
nan = 85.1375
85.1375 = 85.1375
1698
nan = 11.9338
11.9338 = 11.9338
1699
nan = 79.8297
79.8297 = 79.8297
1698
nan = 11.9338
11.9338 = 11.9338
1699
nan = 79.8297
79.8297 = 79.8297
1698
nan = 25.3166
25.3166 = 25.3166
1699
nan = 83.0104
83.0104 = 83.0104
1443
nan = 30.1118
30.1118 = 30.1118
1444
nan = 75.0088
75.0088 = 75.0088
1528
nan = 30.0833
30.0833 = 30.0833
1529
nan = 75.25
75.25 = 75.25
1613
nan = 30.9257
30.9257 = 30.9257
1614
nan = 74.6131
74.6131 = 74.6131
1698
nan = 30.912
30.912 = 30.912
1699
nan = 75.8537
75.8537 = 75.8537
1443
nan = 29.6919
29.6919 = 29.6919
1444
nan = 76.9844
76.9844 = 76.9844
1528
nan = 30.7054
30.7054 = 30.7054
1529
nan = 76.2219
76.2219 = 76.2219
1613
nan = 25.1825
25.1825 = 25.1825
1614
nan = 75.839
75.839 = 75.839
1698
nan = 25.1825
25.1825 = 25.1825
1699
nan = 75.83

In [0]:
a=d.reshape(no_days*20,85)

In [0]:
import pandas as pd
pd.DataFrame(a).to_csv('IndiaNormalized.csv')

# Phased LSTM

In [0]:
from pandas import read_csv
dataframe = read_csv('IndiaNormalized.csv', header=0,engine='python',usecols=range(1,2000))
dataframe.shape

(16440, 85)

In [0]:
from keras.layers import TimeDistributed
import numpy
import matplotlib.pyplot as plt
from pandas import read_csv
import math
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.layers import LSTM
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

Using TensorFlow backend.


In [0]:
print(dataframe.shape)
#print(dataframe.iloc[1,:])
dataset = dataframe.values
#print(dataset[2,:])
dataset = dataset.astype('float32')
#print(dataset.shape)
#print(dataset[0])
scaler = MinMaxScaler(feature_range=(0, 1))
dataset = scaler.fit_transform(dataset)
#print(dataset[1,:])
dataset = dataset.reshape(no_days,no_data_per_day,features)# no. of days, days data, features
#print(dataset.shape)
#print(dataset[0,:,:])

(16440, 85)


In [0]:
print(dataset.shape)
#train_size = int(len(dataset) * 0.67)
#test_size = len(dataset) - train_size
train_size=727
test_size = len(dataset) - train_size
train, test = dataset[0:train_size,:], dataset[train_size:len(dataset),:]
print(train.shape, test.shape)
#print (train)
#print(train[0])
#print(test[0])

(822, 20, 85)
(727, 20, 85) (95, 20, 85)


In [0]:
def create_dataset(dataset, look_back=1):
	dataX, dataY = [], []
	for i in range(len(dataset)-look_back-1):
		a = dataset[i:(i+look_back),:,:]
		dataX.append(a)
		dataY.append(dataset[i + look_back,:,:])
	return numpy.array(dataX), numpy.array(dataY)

In [0]:
import numpy
# reshape into X=t and Y=t+1
look_back = 1
print("Size of data sent:",train.shape)
print(len(train)-look_back-1)
trainX, trainY = create_dataset(train, look_back)
testX, testY = create_dataset(test, look_back)
print("TestX",testX.shape)
print(testY.shape)
print(trainX.shape)
#print(trainY)
print(trainY.shape)
#print(trainX.reshape(no_days,1,no_data_per_day*features))
print(no_data_per_day, features)

print(no_data_per_day*features)
trainX = trainX.reshape(725,1,no_data_per_day*features)#9861
trainY = trainY.reshape(725,no_data_per_day*features)

Size of data sent: (727, 20, 85)
725
TestX (93, 1, 20, 85)
(93, 20, 85)
(725, 1, 20, 85)
(725, 20, 85)
20 85
1700


In [0]:
print(testX[0,:,:,:])

[[[0.47233844 0.37048247 0.14764298 ... 1.         0.6538085  0.53216004]
  [0.43296397 0.3588826  0.4727031  ... 1.         0.8791374  0.22615147]
  [0.07981469 0.11077696 0.19096906 ... 1.         0.9560584  0.22207832]
  ...
  [0.47233844 0.2652576  0.14764298 ... 1.         0.6538085  0.53216004]
  [0.32727244 0.21300356 0.3277374  ... 1.         0.64677835 0.49495173]
  [0.43296397 0.18037808 0.3463416  ... 1.         0.87922335 0.21965837]]]


In [0]:
pip install phased_lstm_keras

In [0]:
import numpy as np
print(np.any(np.isnan(trainX)))
print(np.any(np.isnan(trainY)))

False
False


In [0]:
from keras.layers import Masking
from phased_lstm_keras.PhasedLSTM import PhasedLSTM as PLSTM
a=no_data_per_day*features
print(a)
# create and fit the LSTM network
model = Sequential()
#model.add(Masking(mask_value=3.6122181e+00, batch_input_shape=(None,None, a)))
#(output size,batch_input_shape:input shape of the data)
model.add(PLSTM(a))#, batch_input_shape=(None,None, a),return_sequences=False))
#model.add(TimeDistributed(Dense(5)))
model.add(Dense(a))#,activation='softmax'))
#model.add(Dropout(1))
#model.add(Dense(a))
model.compile(loss='mean_squared_error', optimizer='adam')
#print(model.summary())
model.fit(trainX, trainY, epochs=2, batch_size=30, verbose=2)
#model.fit_generator(generator, steps_per_epoch=1, epochs=500, verbose=0)


1700
Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
Epoch 1/2
 - 25s - loss: 0.3470
Epoch 2/2
 - 22s - loss: 0.0348


In [0]:
model.save('model_india.h5')

In [0]:
trainPredict = model.predict(trainX)
print(trainPredict.shape)
X=trainPredict.reshape(725,no_data_per_day,features)
print(X.shape)
print(type(X))
A=[]
for i in range(len(X-1)):
  a = scaler.inverse_transform(X[i])
  A.append(a)
#print(A)
print(trainY.shape)
Y=trainY.reshape(725,no_data_per_day,features)
B=[]
for i in range(len(Y-1)):
  b = scaler.inverse_transform(Y[i])
  B.append(b)
print(type(B))
trainY=numpy.asarray(B).reshape(725,no_data_per_day*features)
trainPredict=numpy.asarray(A).reshape(725,no_data_per_day*features)
#print(B)
#trainScore = math.sqrt(mean_squared_error(trainY, trainPredict))

(725, 1700)
(725, 20, 85)
<class 'numpy.ndarray'>
(725, 1700)
<class 'list'>


In [0]:
testX = testX.reshape(93,1,no_data_per_day*features)
print(testX.shape)
testPredict = model.predict(testX)
print(testPredict.shape)
X=testPredict.reshape(93,no_data_per_day,features)
A=[]
for i in range(len(X-1)):
  a = scaler.inverse_transform(X[i])
  print('Append:',a)
  A.append(a)
#print(A)
print('testY',testY.shape)
Y=testY.reshape(93,no_data_per_day,features)
B=[]
for i in range(len(Y-1)):
  b = scaler.inverse_transform(Y[i])
  B.append(b)
print(type(B))
testY=numpy.asarray(B).reshape(93,no_data_per_day*features)
testPredict=numpy.asarray(A).reshape(93,no_data_per_day*features)
#print(B)
#trainScore = math.sqrt(mean_squared_error(trainY, trainPredict))

(93, 1, 1700)
(93, 1700)
Append: [[ 1.26487     1.510152    2.496195   ...  4.1016417  23.309803
  81.80236   ]
 [ 1.0783647   1.6577069   2.5213327  ...  4.0432043  25.002823
  80.928604  ]
 [ 0.92737406  1.7071613   2.6444511  ...  4.11666    24.280277
  78.88396   ]
 ...
 [ 1.3237218   1.7911774   2.6634042  ...  4.089477   24.175592
  79.63895   ]
 [ 1.1283325   1.9325329   2.7997901  ...  4.0695214  23.478142
  80.47438   ]
 [ 1.4534911   2.051024    2.819297   ...  4.048192   23.550058
  78.99261   ]]
Append: [[ 1.2648576   1.5102022   2.4962795  ...  4.101654   23.30982
  81.80214   ]
 [ 1.0782604   1.6576715   2.5214643  ...  4.043257   25.003004
  80.928375  ]
 [ 0.92733526  1.7072835   2.64446    ...  4.1167245  24.280352
  78.88386   ]
 ...
 [ 1.3236978   1.7911754   2.663463   ...  4.089481   24.1752
  79.63886   ]
 [ 1.1284504   1.9327025   2.7998974  ...  4.069463   23.478086
  80.474495  ]
 [ 1.4534487   2.0510345   2.8194056  ...  4.0482717  23.549603
  78.99227   ]]
Ap

In [0]:
print(testPredict.shape)
lastPred=testPredict[91:92,:]
print(lastPred.shape)
lastPredX = numpy.reshape(lastPred, (lastPred.shape[0], 1, 1700))#1700=85*20
predictNext = model.predict(lastPredX)
P=predictNext.reshape(1,no_data_per_day,features)
PN=[]
for i in range(len(P-1)):
  a = scaler.inverse_transform(P[i])
  print('Append:',a)
  A.append(a)
print("Next day prediction Done")

(93, 1700)
(1, 1700)
Append: [[ 1.2653099   1.5093342   2.4965055  ...  4.102462   23.30895
  81.80469   ]
 [ 1.0801361   1.6579028   2.520856   ...  4.042496   25.001575
  80.92603   ]
 [ 0.92671365  1.7072376   2.645689   ...  4.115753   24.27299
  78.87824   ]
 ...
 [ 1.3231516   1.7914999   2.6639562  ...  4.089597   24.172182
  79.63907   ]
 [ 1.128478    1.932687    2.8002794  ...  4.070392   23.47869
  80.47895   ]
 [ 1.4532856   2.0512185   2.819458   ...  4.048636   23.557816
  78.9943    ]]
Next day prediction Done


In [0]:
days = input("Number of Days to predict?")
days=int(days)
for i in range(days):
  Next=predictNext
  todayPredictionX = numpy.reshape(Next, (lastPred.shape[0], look_back, 1700))
  predictNext = model.predict(todayPredictionX)
  P=predictNext.reshape(1,no_data_per_day,features)
  for i in range(len(P-1)):
    a = scaler.inverse_transform(P[i])
    print('Append:',a)
    A.append(a)

Number of Days to predict?46
Append: [[ 1.2648374  1.5101873  2.4962375 ...  4.101755  23.309961  81.80223  ]
 [ 1.0782849  1.6577741  2.5213723 ...  4.043308  25.003187  80.92845  ]
 [ 0.9273156  1.7072704  2.6444654 ...  4.116825  24.280003  78.88383  ]
 ...
 [ 1.3237793  1.791177   2.663463  ...  4.0897126 24.175507  79.63915  ]
 [ 1.1283659  1.9327384  2.799896  ...  4.069566  23.478065  80.474686 ]
 [ 1.4535383  2.0511036  2.8194351 ...  4.048358  23.549978  78.99244  ]]
Append: [[ 1.2648371  1.5101873  2.496238  ...  4.101755  23.309963  81.80223  ]
 [ 1.0782847  1.6577747  2.5213723 ...  4.043308  25.003187  80.92845  ]
 [ 0.9273158  1.7072704  2.644466  ...  4.116825  24.280003  78.88383  ]
 ...
 [ 1.32378    1.7911774  2.663463  ...  4.089713  24.175507  79.63915  ]
 [ 1.1283659  1.9327384  2.799896  ...  4.069566  23.478067  80.474686 ]
 [ 1.453538   2.0511038  2.819435  ...  4.048358  23.549978  78.99244  ]]
Append: [[ 1.2648371  1.5101873  2.496238  ...  4.101755  23.309963

In [0]:
import numpy as np
W = np.array(A)
W.shape

(140, 20, 85)

In [0]:
P = W.reshape(W.shape[0],20*85)

In [0]:
pd.DataFrame(P).to_csv('Predicted.csv')

#Normalize Output

In [0]:
from pandas import read_csv
dataframe = read_csv('Predicted.csv', header=0,engine='python',usecols=range(1,20000))
print(dataframe.shape)
d=dataframe.values

(140, 1700)


In [0]:

c=0
#for i in range(19):
 # print(d[0,85+c],d[0,86+c])
 # c+=87
x=0;

for i in range(d.shape[0]-1):
  c=0
  for j in range(20):
    #print(i)
    #print(d[i,85+c],d[i+1,86+c])
    #print(d[i,83+c],d[i+1,83+c])
    #print(abs(d[i,83+c]-d[i+1,83+c])<0.0001)
    if abs(d[i,83+c]-d[i+1,83+c])<0.0001:
      #print(abs(d[i,83+c]-d[i+1,83+c]))
      x+=1
      d[i,83+c]=0
      d[i,84+c]=0
    c+=85
print("NO. of data removed",x)
  

NO. of data removed 1304


In [0]:
import pandas as pd

pd.DataFrame(d).to_csv('Pred1.csv')

In [0]:
print(pd.DataFrame(d).shape)
df = pd.DataFrame(d)
d = d.reshape(d.shape[0],20,85)

(140, 1700)


In [0]:
pip install reverse_geocoder

In [0]:
W=d

In [0]:
coordinates = (-0.487803934,	-0.275010895)
result = rg.search(coordinates)
print(result[0])

NameError: ignored

In [0]:
dt = datetime.datetime.strptime("2019-12-2", '%Y-%m-%d')
date='{0}/{1}/{2:01}'.format(dt.month %100, dt.day % 100, dt.year)
print(date)

12/2/2019


In [0]:
print(d.shape)

W=d[127:139,:]
print(W.shape)

(139, 20, 85)
(12, 20, 85)


In [0]:
import datetime
import pandas as pd
import reverse_geocoder as rg 
mydate = datetime.date(2019,1,1)  #year, month, day
i=0
row_list=[]

for i in range(W.shape[0]):
  dt = datetime.datetime.strptime(str(mydate), '%Y-%m-%d')
  date='{0}/{1}/{2:02}'.format(dt.month%100, dt.day%100, dt.year)
  print(date)
  for j in range(20):
    if  W[i,j,83]==0:
      continue
    revGeo=dict.fromkeys(['date','lat','lon','state','country','place'])
    
    #revGeo['lat']= W[i,j,83]
    #revGeo['lon']=W[i,j,84]
    #print(W[i,j,69],W[i,j,70])
    coordinates = (W[i,j,83],W[i,j,84])
    #print(coordinates)
    result = rg.search(coordinates)
    #print(result[0])
    #print(result[0]["cc"])
    if(result[0]['cc']=='IN'):
      #print(result[0]['admin1'])
      revGeo['date']=date
      revGeo['lat']=result[0]['lat']
      revGeo['lon']=result[0]['lon']
      revGeo['state']=result[0]['admin1']
      revGeo['country']=result[0]['cc']
      revGeo['place']=result[0]['name']
    row_list.append(revGeo)
  mydate=mydate+datetime.timedelta(days=1)
  #print()
  #print()


1/1/2019
Loading formatted geocoded file...
1/2/2019
1/3/2019
1/4/2019
1/5/2019
1/6/2019
1/7/2019
1/8/2019
1/9/2019
1/10/2019
1/11/2019
1/12/2019
1/13/2019
1/14/2019
1/15/2019
1/16/2019
1/17/2019
1/18/2019
1/19/2019
1/20/2019
1/21/2019
1/22/2019
1/23/2019
1/24/2019
1/25/2019
1/26/2019
1/27/2019
1/28/2019
1/29/2019
1/30/2019
1/31/2019
2/1/2019
2/2/2019
2/3/2019
2/4/2019
2/5/2019
2/6/2019
2/7/2019
2/8/2019
2/9/2019
2/10/2019
2/11/2019
2/12/2019
2/13/2019
2/14/2019
2/15/2019
2/16/2019
2/17/2019
2/18/2019
2/19/2019
2/20/2019
2/21/2019
2/22/2019
2/23/2019
2/24/2019
2/25/2019
2/26/2019
2/27/2019
2/28/2019
3/1/2019
3/2/2019
3/3/2019
3/4/2019
3/5/2019
3/6/2019
3/7/2019
3/8/2019
3/9/2019
3/10/2019
3/11/2019
3/12/2019
3/13/2019
3/14/2019
3/15/2019
3/16/2019
3/17/2019
3/18/2019
3/19/2019
3/20/2019
3/21/2019
3/22/2019
3/23/2019
3/24/2019
3/25/2019
3/26/2019
3/27/2019
3/28/2019
3/29/2019
3/30/2019
3/31/2019
4/1/2019
4/2/2019
4/3/2019
4/4/2019
4/5/2019
4/6/2019
4/7/2019
4/8/2019
4/9/2019
4/10/2019
4

In [0]:
pd.DataFrame(row_list).to_csv('IndiaPrediction2019New.csv')

In [0]:
with open('IndiaPrediction2019New.txt', 'w') as f:
    for item in row_list:
        f.write("%s\n" % item)

In [0]:
import json

with open('IndiaPrediction2019New.json', 'w') as f:
    f.write("[")
    for item in row_list:
        f.write("%s,\n" % item)
    f.write("]")